修复在 template 中定义 compileTemplate 属性无效的问题
ecomfe/san-loader pull request #34
Opened 2021-06-17 10:41 UTC by vanishcode

2021-06-17 12:14 UTC, jinzhan commented on lib/loader.js
> -            if (compileTemplateTypes.includes(query.compileTemplate)) {
这个地方建议处理下query，兼容下camelCase的写法

2021-06-18 03:43 UTC, jinzhan commented on lib/loader.js
> +
这个地方的loader处理交给用户定义的rule，需要注意的是aNodeUtils.parseTemplate放到最后阶段处理。

2021-06-18 07:53 UTC, ksky521 requested changes

2021-06-18 07:53 UTC, ksky521 commented on lib/loader.js
> +
这里很早就支持了：https://github.com/ecomfe/san-loader/blob/master/examples/src/components/comp-pug.san

2021-06-18 09:52 UTC, jinzhan commented on lib/loader.js
> +
这个地方是要解决的是template包行lang参数，解析aNode存在的bug。

2021-06-21 02:52 UTC, Lohoyo commented on lib/loader.js
> +        if (Object.hasOwnProperty.call(query, key) && key.includes('-')) {
这里为什么要用 `call` 而不是直接 `query.hasOwnProperty(key)`？

2021-06-24 07:00 UTC, ksky521 approved these changes

2021-06-24 07:01 UTC, merged